### PR TITLE
Crash when casting NaN or infinite decimals

### LINKED ISSUE #2547: Crash when validating NaN number
### Environment
* Ecto version (mix deps): 2.10

### Current behavior
When validating
```
MyStruct{}
|> cast(%{my_field: "NaN"})
|> validate_required([:my_field])
|> validate_number(: my_field, greater_than: 0, less_than: 100)
```
ecto crashes with
```
** (CaseClauseError) no case clause matching: #Decimal<NaN>
(decimal) lib/decimal.ex:349: Decimal.cmp/2
(ecto) lib/ecto/changeset.ex:1727: Ecto.Changeset.validate_number/6
(elixir) lib/enum.ex:2914: Enum.find_value_list/3
(ecto) lib/ecto/changeset.ex:1312: Ecto.Changeset.validate_change/3
```
### Expected behavior
'validate_required' should check if the number is not NaN (just like it checks if string is not empty)
'validate_number' should not try to compare with NaN (or use Decimal.compare/2 instead of Decimal.cmp/2 and ignore NaN results)

### PR DESCRIPTION
**Pull request by wojtekmach**
Closes #2547

### CODE REVIEW

File: test/ecto/type_test.exs [hunk 1]
```diff
@@ -106,6 +106,18 @@ defmodule Ecto.TypeTest do
...
+    assert_raise Ecto.CastError, ~r{cannot cast "nan" to :decimal}, fn ->
+      cast(:decimal, "nan")
+    end
+
+    assert_raise Ecto.CastError, ~r{cannot cast #Decimal<NaN> to :decimal}, fn ->
+      cast(:decimal, Decimal.new("NaN"))
+    end
+
+    assert_raise Ecto.CastError, ~r{cannot cast #Decimal<Infinity> to :decimal}, fn ->
+      cast(:decimal, Decimal.new("Infinity"))
```
Comment (wojtekmach) [inline test/ecto/type_test.exs]: the ticket didn't mention infinity, but I'm crashing on them by the same token that it's not what people may have expected. Also, pg doesn't support infinite decimals (numerics)

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
