### PR TITLE
Fix check_field_type! for invalid composite types

### LINKED ISSUE #3371: The schema validation type for `{:array, inner_type} `  is not working as the query one
### Environment

* Elixir version: 1.10.1

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): postgres (PostgreSQL) 12.2

* Ecto version: 3.4.4

* Database adapter and version (mix deps): Postgrex 0.15.5

* Operating system: Mac OS and Alpine Linux

### Current behavior

The schema check for `{:array, inner_type} `  is not working as the query one.

### Expected behavior

The schema validation for types for `{:array, inner_type} ` is not working as the query one.

When we create a field with `{:array, :jsonb}`  in the schema and this column is empty in the database we don't receive any error on compilation time. 

But when we run a query in the table that has this column and has a value we receive an exception telling us that the `:jsonb` does not have a type definition.

```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function :jsonb.type/0 is undefined (module :jsonb is not available)
        :jsonb.type()
        (ecto 3.4.4) lib/ecto/type.ex:307: Ecto.Type.type/1
        (ecto 3.4.4) lib/ecto/type.ex:916: Ecto.Type.adapter_load/3
        (ecto 3.4.4) lib/ecto/repo/queryable.ex:381: Ecto.Repo.Queryable.struct_load!/6
        (ecto 3.4.4) lib/ecto/repo/queryable.ex:213: anonymous fn/5 in Ecto.Repo.Queryable.preprocessor/3
        (elixir 1.10.1) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
        (ecto 3.4.4) lib/ecto/repo/queryable.ex:200: Ecto.Repo.Queryable.execute/4
        (ecto 3.4.4) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
        (ecto 3.4.4) lib/ecto/repo/queryable.ex:112: Ecto.Repo.Queryable.one/3
```

I would expect to have the exception also on compilation time, but it is not happening because we are checking it differently. 
At the Schema level, we check a tuple, and at the Query level, we check only the type.

```
iex(1)> Ecto.Type.primitive?(:jsonb)
false
iex(2)> Ecto.Type.primitive?({:array, :jsonb})
true
```

**Schema**

[https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/schema.ex#L2050-L2051](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/schema.ex#L2050-L2051)

**Query**

[https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/type.ex#L300-L311](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/type.ex#L300-L311)

### Application Example

[ecto_bug.zip](https://github.com/elixir-ecto/ecto/files/5044145/ecto_bug.zip)

### PR DESCRIPTION
**Pull request by Eiji7**
closes #3371

### CODE REVIEW

File: lib/ecto/schema.ex [hunk 1]
```diff
@@ -2041,12 +2041,18 @@ defmodule Ecto.Schema do
                            "(no time zone information) or :utc_datetime (time zone is set to UTC)"
   end
 
-  defp check_field_type!(name, type, opts) do
+  defp check_field_type!(name, type, opts, full_type \\ nil) do
+    full_type = if is_nil(full_type), do: type, else: full_type
```
Comment (josevalim) [inline lib/ecto/schema.ex:2045]: Instead of passing it as `nil`, maybe we should change the caller to also pass `type` here and we never have `nil`?

File: lib/ecto/schema.ex [hunk 2]
```diff
@@ -2041,12 +2041,18 @@ defmodule Ecto.Schema do
...
+
     cond do
       type == :any and !opts[:virtual] ->
         raise ArgumentError, "only virtual fields can have type :any, " <>
                              "invalid type for field #{inspect name}"
 
+      is_tuple(type) and tuple_size(type) == 2 and type |> elem(0) |> Ecto.Type.composite?() ->
+        inner_type = elem(type, 1)
+        check_field_type!(name, inner_type, opts, type)
```
Comment (josevalim) [inline lib/ecto/schema.ex:2054]: If it is a two element tuple, it is always composite:

```suggestion
      is_tuple(type) and tuple_size(type) == 2 ->
        check_field_type!(name, elem(type, 1), opts, type)
```

We will also need a three element tuple check for parameterized types. :D

Comment (Eiji7) [reply lib/ecto/schema.ex:2054]: @josevalim 
> If it is a two element tuple, it is always composite:

Sorry, I do not understand that. If so then why we have a `Ecto.Type.composite?` function and how would let's say `{:jsonb, :jsonb}` work?

> We will also need a three element tuple check for parameterized types. :D

Ah right, I forgot about that

File: lib/ecto/schema.ex [hunk 3]
```diff
@@ -2035,18 +2035,22 @@ defmodule Ecto.Schema do
...
   end
 
-  defp check_field_type!(name, type, opts) do
+  defp check_field_type!(name, type, full_type, opts) do
     cond do
       type == :any and !opts[:virtual] ->
         raise ArgumentError, "only virtual fields can have type :any, " <>
                              "invalid type for field #{inspect name}"
 
+      is_tuple(type) and tuple_size(type) == 2 and type |> elem(0) |> Ecto.Type.composite?() ->
```
Comment (josevalim) [inline lib/ecto/schema.ex:2050]: Ah, good point. Can we at least move this to a private function? so we just call it as `composite?(type) ->` or, even better, `inner_type = inner_from_composite(type) ->`. WDYT?

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
