### PR TITLE
Share loading/dumping logic between embed and typed maps, closes #2637

### LINKED ISSUE #2637: Error when loading specific values in fields of type {:map, :float}
### Environment

* Elixir version (elixir -v): Elixir 1.6.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6.7
* Ecto version (mix deps): master branch
* Database adapter and version (mix deps): postgrex 0.14.0-dev
* Operating system: Debian Jessie

### Current behavior
When I have a schema with a field of type `{:map, :array`}, some values are parsed to exponential floats and are saved as integers in the database. 

For example,  `%{"50" => 416500.0}` fails, because it is saved as an integer 416500, even after `Float.parse(416500)`, which returns an exponential form for it. I don't know if it has something to do with the jsonb fields, but for simple `float`fields it works.

```elixir
Float.parse("416500")
{4.165e5, ""}
```
 
I've added an example to ecto integration tests that shows the break point. See this commit https://github.com/tallysmartins/ecto/commit/5048199197ff2bd3e1480cd8286931f2d07cddde and the correspondent [build on Travis-ci](https://travis-ci.org/tallysmartins/ecto/builds/411507876)

```bash
     ** (ArgumentError) cannot load `%{"50" => 416500}` as type {:map, :float} for field `scores` in schema Ecto.Integration.Post
     code: assert [_] = TestRepo.all from p in Post, where: p.title not in []
     stacktrace:
       (ecto) lib/ecto/schema.ex:1794: Ecto.Schema.load!/5
       (ecto) lib/ecto/schema.ex:1742: Ecto.Schema.safe_load_zip/4
       (ecto) lib/ecto/schema.ex:1743: Ecto.Schema.safe_load_zip/4
       (ecto) lib/ecto/schema.ex:1730: Ecto.Schema.__safe_load__/6
       (ecto) lib/ecto/repo/queryable.ex:316: Ecto.Repo.Queryable.process_source/6
       (ecto) lib/ecto/repo/queryable.ex:191: anonymous fn/6 in Ecto.Repo.Queryable.preprocessor/3
       (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
       (ecto) lib/ecto/repo/queryable.ex:152: Ecto.Repo.Queryable.execute/4
       (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
       integration_test/cases/repo.exs:44: (test)
```

### Expected behavior
Save and load the field the same way as simple float field.

### PR DESCRIPTION
**Pull request by josevalim**

### CODE REVIEW

File: integration_test/cases/type.exs [hunk 1]
```diff
@@ -203,6 +203,14 @@ defmodule Ecto.Integration.TypeTest do
            [%{"foo" => "http://foo.com", "bar" => "http://bar.com"}]
   end
 
+  @tag :map_type
+  test "typed float map" do
+    post = TestRepo.insert!(%Post{intensities: %{"foo" => 1.0, "bar" => 416500.0}})
+
+    assert TestRepo.all(from p in Post, where: p.id == ^post.id, select: p.intensities) ==
+           [%{"foo" => 1.0, "bar" => 416500}]
+  end
```
Comment (ericmj) [inline integration_test/cases/type.exs]: Can you add a test that loads a value that was persisted as a string? This test relies on the implementation detail of postgres json.

Comment (josevalim) [reply integration_test/cases/type.exs]: @ericmj This test is wrong, it is meant to return float. :(

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
