### PR TITLE
Provide beter errors for `Ecto.Type.cast`

### LINKED ISSUE #2746: Allow for beter errors for `Ecto.Type`
At the moment, you can only pass `:error` when a `cast` fails with `Ecto.Type`. 

It would be really useful to be able to pass custom error messages. For example `{:error, "some custom error message}`, to help finding out why something failed.

### PR DESCRIPTION
**Pull request by tcoopman**
This fixes #2746 

Checking if this is the right approach. If it is, then I'll clean it up, update the documentation,...

Feedback is very welcome, because I've got no idea if this is the way you would solve it.

### CODE REVIEW

File: lib/ecto/changeset.ex [hunk 1]
```diff
@@ -528,6 +528,11 @@ defmodule Ecto.Changeset do
         {changes, errors, valid?}
       :invalid ->
         {changes, [{key, {"is invalid", [type: type, validation: :cast]}} | errors], false}
+      {:invalid, custom_errors} ->
+        {msg, custom_errors} = Keyword.pop(custom_errors, :message)
+        msg = msg || "is invalid"
+        new_errors = Keyword.merge([type: type, validation: :cast], custom_errors)
```
Comment (fertapric) [inline lib/ecto/changeset.ex]: Should Ecto raise an error if the custom error contains reserved keys like `:type` and `:validation`?

File: lib/ecto/changeset.ex [hunk 2]
```diff
@@ -569,6 +574,9 @@ defmodule Ecto.Changeset do
 
           :error ->
             :invalid
```
Comment (josevalim) [inline lib/ecto/changeset.ex]: Let's change this to return `{:invalid, message: "is invalid"}`.

File: lib/ecto/changeset.ex [hunk 3]
```diff
@@ -528,6 +528,11 @@ defmodule Ecto.Changeset do
         {changes, errors, valid?}
       :invalid ->
         {changes, [{key, {"is invalid", [type: type, validation: :cast]}} | errors], false}
+      {:invalid, custom_errors} ->
+        {msg, custom_errors} = Keyword.pop(custom_errors, :message)
+        msg = msg || "is invalid"
```
Comment (josevalim) [inline lib/ecto/changeset.ex]: Should we raise if the message is not present? Thoughts @wojtekmach?

File: lib/ecto/changeset.ex (hunk 1 above)
Comment (josevalim) [reply lib/ecto/changeset.ex]: I think we want to allow the user to change `validation` but I think is no reason to allow the type to be changed. I would go with something like:

```elixir
[type: type] ++ Keyword.put_new(custom_errors, :validation, :cast)
```

**Comment by josevalim** [comment]
Thanks @tcoopman! Note that we also need a test for what happens when you declare the type to be `{:array, CustomError}` and `{:map, CustomError}`. I think you will have to do some changes in `Ecto.Type` for this to work. I think we will have to drop the information that you return today and make the whole array/map as invalid (without information of its inner contents).

File: lib/ecto/changeset.ex (hunk 3 above)
Comment (fertapric) [reply lib/ecto/changeset.ex]: I would make it optional to reduce boilerplate. 

For example, `{:error, reason: :invalid_country}` would need to rewritten to `{:error, reason: :invalid_country, message: "is invalid"}` even if the user does not want to provide a custom error message.

**Comment by wojtekmach** [comment]
@josevalim do we need to make similar changes to `load` and `dump` callbacks? I don't think we do as we don't use them for errors, but just double-checking.

**Comment by josevalim** [comment]
@wojtekmach i don't think so, yeah.

**Comment by zachdaniel** [comment]
We should probably change the behavior as well to indicate this new return format: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/type.ex#L648

File: lib/ecto/changeset.ex (hunk 1 above)
Comment (tcoopman) [reply lib/ecto/changeset.ex]: I've changed it to the remarks of @josevalim. If we want to inform the user that we are overriding the `type`, that's something for the docs?

**Comment by tcoopman** [comment]
> Thanks @tcoopman! Note that we also need a test for what happens when you declare the type to be `{:array, CustomError}` and `{:map, CustomError}` and you pass a list/map with an invalid entry. I think you will have to do some changes in `Ecto.Type` for this to work. I think we will have to drop the information that you return today and make the whole array/map as invalid (without information of its inner contents).

So you mean a test like this:

```
 defmodule Ecto.ChangesetTest do
     schema "custom_error" do
       field :custom_error, CustomError
       field :custom_error_2, CustomError2
+      field :array_custom_error, {:array, CustomError}
     end
   end
 
@@ -269,6 +270,15 @@ defmodule Ecto.ChangesetTest do
     refute changeset.valid?
   end
 
+  test "cast/4: field has a custom invalid error message on an array field" do
+    params = %{"array_custom_error" => [:error]}
+    struct = %CustomErrorTest{}
+
+    changeset = cast(struct, params, ~w(array_custom_error)a)
+    assert changeset.errors == [array_custom_error: {"is invalid", [type: Ecto.ChangesetTest.CustomError, validation: :cast, reason: :foobar]}]
+    refute changeset.valid?
+  end
```

Should the error be changed to note that it is an error in an array?

**Comment by josevalim** [comment]
@tcoopman I don't think we should propagate the internal error, because it can get very confusing. So I would suggest this:

```
assert changeset.errors == [array_custom_error: {"is invalid", [type: {:array, Ecto.ChangesetTest.CustomError}, validation: :cast]}]
```

File: lib/ecto/changeset.ex [hunk 4]
```diff
@@ -568,7 +570,10 @@ defmodule Ecto.Changeset do
             end
 
           :error ->
-            :invalid
+            {:invalid, message: "is invalid"}
```
Comment (josevalim) [inline lib/ecto/changeset.ex]: Since we do have a default message, I think we can go with:

```suggestion
            {:invalid, []}
```

File: lib/ecto/changeset.ex [hunk 5]
```diff
@@ -568,7 +570,10 @@ defmodule Ecto.Changeset do
...
+
+          {:error, custom_errors} ->
```
Comment (josevalim) [inline lib/ecto/changeset.ex]: I would add a guard, just in case:

```suggestion
          {:error, custom_errors} when is_list(custom_errors) ->
```

File: lib/ecto/changeset.ex [hunk 6]
```diff
@@ -526,8 +526,10 @@ defmodule Ecto.Changeset do
         {Map.put(changes, key, value), errors, valid?}
       :missing ->
         {changes, errors, valid?}
-      :invalid ->
-        {changes, [{key, {"is invalid", [type: type, validation: :cast]}} | errors], false}
+      {:invalid, custom_errors} ->
+        {message, custom_errors} = Keyword.pop(custom_errors, :message, "is invalid")
+        new_errors = [type: type] ++ Keyword.put_new(custom_errors, :validation, :cast)
+        {changes, [{key, {message, new_errors}} | errors], false}
```
Comment (josevalim) [inline lib/ecto/changeset.ex]: This looks beautiful now, thank you!

**Comment by tcoopman** [comment]
> ```
> assert changeset.errors == [array_custom_error: {"is invalid", [type: {:array, Ecto.ChangesetTest.CustomError}, validation: :cast]}]
> ```

I've changed this and erased the custom error in `Ecto.Type`.
I've also started to add some documentation. Not sure if the style is correct though.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

File: lib/ecto/changeset.ex [hunk 7]
```diff
@@ -526,8 +526,10 @@ defmodule Ecto.Changeset do
         {Map.put(changes, key, value), errors, valid?}
       :missing ->
         {changes, errors, valid?}
-      :invalid ->
-        {changes, [{key, {"is invalid", [type: type, validation: :cast]}} | errors], false}
+      {:invalid, custom_errors} ->
+        {message, custom_errors} = Keyword.pop(custom_errors, :message, "is invalid")
+        new_errors = [type: type] ++ Keyword.put_new(custom_errors, :validation, :cast)
```
Comment (fertapric) [inline lib/ecto/changeset.ex]: If the user provides the `:type` key, the resulting error will contain two `:type` keys, which might lead to some side effects similar to overriding the `:type` key. For example:

```elixir
iex(1)> errors = [type: MyType] ++ [type: MyErrorType, validation: :my_validation]
[type: MyType, type: MyErrorType, validation: :my_validation]
iex(2)> Enum.into(errors, %{})
%{type: MyErrorType, validation: :my_validation}
```
