### PR TITLE
Fix assoc schema_prefix on through-associations

### LINKED ISSUE #1746: assoc doesn't respect @schema_prefix on through-associations
While **preloading** "through-associations" on a prefixed schema works fine, requesting them with **assoc** doesn't respect the @schema_prefix.

### Environment

* Elixir version (elixir -v): 1.3.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MariaDB 
* Ecto version (mix deps): 2.0.5
* Database adapter and version (mix deps): mariaex 0.7.8
* Operating system: arch linux

### Current behavior
```elixir
defmodule Hotel do
  use Ecto.Schema
  @schema_prefix "br_dev"

  schema "hotel_hotels" do
    has_many :room_categories, Hotel.RoomCategory
    has_many :rooms, through: [:room_categories, :rooms]
  end
end

defmodule Hotel.RoomCategory do
  use Ecto.Schema
  @schema_prefix "br_dev"

  schema "hotel_room_categories" do
    belongs_to :hotel, Hotel
    has_many :rooms, Hotel.Room
  end
end

defmodule Hotel.Room do
  use Ecto.Schema
  @schema_prefix "br_dev"

  schema "hotel_rooms" do
    belongs_to :room_category, Hotel.RoomCategory
    has_one :hotel, through: [:room_category, :hotel]
  end
end

h = Repo.get Hotel, 1
Repo.preload(h, :rooms) # works fine, respects @schema_prefix
# [debug] QUERY OK source="hotel_room_categories" db=0.5ms SELECT h0.`id`, h0.`hotel_id`, h0.`hotel_id` FROM `br_dev`.`hotel_room_categories` AS h0 WHERE (h0.`hotel_id` = ?) ORDER BY h0.`hotel_id` [1]
# [debug] QUERY OK source="hotel_rooms" db=0.5ms decode=0.1ms SELECT h0.`id`, h0.`room_category_id`, h0.`room_category_id` FROM `br_dev`.`hotel_rooms` AS h0 WHERE (h0.`room_category_id` IN (?,?,?,?,?,?,?,?)) ORDER BY h0.`room_category_id` [4, 5, 6, 163, 164, 165, 166, 167]

Repo.all Ecto.assoc(h, :rooms) # fails for ignoring @schema_prefix on through-association
# [debug] QUERY ERROR source="hotel_rooms" db=0.1ms SELECT DISTINCT h0.`id`, h0.`room_category_id` FROM `hotel_rooms` AS h0 INNER JOIN `hotel_room_categories` AS h1 ON h1.`hotel_id` = ? WHERE (h0.`room_category_id` = h1.`id`) [1]
# ** (Mariaex.Error) (1146): Table 'br.hotel_rooms' doesn't exist

Repo.all Ecto.assoc(h, :room_categories) # but direct associations work fine with @schema_prefix
# [debug] QUERY OK source="hotel_room_categories" db=0.5ms SELECT h0.`id`, h0.`hotel_id` FROM `br_dev`.`hotel_room_categories` AS h0 WHERE (h0.`hotel_id` = ?) [1]

```
### Expected behavior
`Repo.all Ecto.assoc(h, :rooms)` should respect the "br_dev" schema_prefix.

### PR DESCRIPTION
**Pull request by shhavel**
Fix #1746
Added two schemes in integration tests: `PostWithPrefix`, `CommentWithPrefix` to test through association.
Tests contain generated SQL expectations for clarity.

### CODE REVIEW

File: integration_test/support/schemas.exs [hunk 1]
```diff
@@ -271,3 +271,50 @@ defmodule Ecto.Integration.PostUserCompositePk do
...
 end
+
+defmodule Ecto.Integration.Hotel do
+  @moduledoc """
+  This module is used to test:
+
+    * Ecto.assoc schema_prefix on through-associations
+
+  """
+  use Ecto.Integration.Schema
```
Comment (josevalim) [inline integration_test/support/schemas.exs]: I would like to avoid adding multiple schemas more. Could we do a single new schema? Maybe call it PostWithPrefix?

File: lib/ecto/association.ex [hunk 2]
```diff
@@ -189,8 +189,9 @@ defmodule Ecto.Association do
     rewrite_ix = assoc.ix
     [assoc|joins] = Enum.map([assoc|joins], &rewrite_join(&1, rewrite_ix))
 
+    {_, schema} = assoc.source
     %{query | wheres: [assoc_to_where(assoc)|query.wheres], joins: joins,
-              from: merge_from(query.from, assoc.source), sources: nil}
+              from: merge_from(query.from, assoc.source), sources: nil, prefix: schema.__schema__(:prefix)}
```
Comment (josevalim) [inline lib/ecto/association.ex]: I think the prefix should be set here: https://github.com/shhavel/ecto/blob/51e69a35b036ebf3efc4abe625b8d829f86b5011/lib/ecto/association.ex#L163

Only on the right side of `||`. If a query is given, we should likely respect the prefix in the query because we are going to respect the from in that query too.

**Comment by josevalim** [comment]
Thank you :heart: I have added some comments!

**Comment by shhavel** [comment]
@josevalim Please review.

File: lib/ecto/adapters/mysql/connection.ex [hunk 3]
```diff
@@ -495,7 +495,7 @@ if Code.ensure_loaded?(Mariaex) do
         case elem(sources, pos) do
           {table, schema} ->
             name = String.first(table) <> Integer.to_string(pos)
-            {quote_table(prefix, table), name, schema}
+            {quote_table(prefix || (schema && schema.__schema__(:prefix)), table), name, schema}
```
Comment (josevalim) [inline lib/ecto/adapters/mysql/connection.ex]: Generally we avoid calling schema functions in the adapter. The idea is that the adapter already receives all the data pre-processed. This would also break cases where the prefix is explicitly set to nil.

Is there any reason why you preferred to change it here instead of setting in the ecto/association.ex file when the query is built as previously mentioned?

Comment (shhavel) [inline lib/ecto/adapters/mysql/connection.ex]: The query has only one prefix that is applied to all tables in SQL query,
this does not work for cross-schema queries, e.g.

```sql
SELECT * FROM "my_prefix"."comments" INNER JOIN "posts" ...
```
In this example `my_prefix` should be applied only to `comments`,
but if it will be set to query it will be set to both `comments` and `posts`.

I've create a test for this case - https://github.com/shhavel/ecto/blob/bdad903e3ad09458099b4a13d53ea4f92393acc8/integration_test/cases/assoc.exs#L162

Comment (josevalim) [inline lib/ecto/adapters/mysql/connection.ex]: We don't support queries across schemas by design. If we are going to support it, we need to revisit all cases and scenarios, it should not be handled in the adapter because the adapter may not have enough information to decide which one to use.

Comment (shhavel) [inline lib/ecto/adapters/mysql/connection.ex]: Ok, will do. Thanks

Comment (shhavel) [inline lib/ecto/adapters/mysql/connection.ex]: Changed back to set prefix in `ecto/association.ex`.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
@shhavel I had an idea of how we could use unit tests instead and I moved the schemas you wrote to unit tests in 57eb1c290c6f2491c7b5970c8be1d3edc67d9f8e.
