### PR TITLE
Fix CastError when casting list to embeds_one

### LINKED ISSUE #3557: Array input to embeds_one throws Ecto.CastError
### Environment

* Elixir version (elixir -v): `Elixir 1.11.3 (compiled with Erlang/OTP 23)`
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): `N/A`
* Operating system: `MacOS 10.15.7`

Libs:
* ecto 3.5.7 (Hex package) (mix)
  locked at 3.5.7 (ecto) 04c4e69d
  ok
* ecto_sql 3.5.4 (Hex package) (mix)
  locked at 3.5.4 (ecto_sql) 1fff1a28
  ok
* myxql 0.4.5 (Hex package) (mix)
  locked at 0.4.5 (myxql) 40a6166a
  ok

### Current behavior

We are currently attempting to use Ecto schemas / changesets as an input validator.  Given some unknown input from the outside world, we want an  `Ecto.Changeset` that states whether the input was valid or invalid. There is no actual database involved in this piece of code.

Sample code: 
```elixir
defmodule Parent do
  use Ecto.Schema
  import Ecto.Changeset

  schema "parents" do
    field :name, :string

    embeds_one :child, Child do
      field :name, :string
      field :age,  :integer
    end
  end

  def changeset(schema, params) do
    schema
    |> cast(params, [:name])
    |> cast_embed(:child, with: &child_changeset/2)
  end

  defp child_changeset(schema, params) do
    schema
    |> cast(params, [:name, :age])
  end

  # #Ecto.Changeset<
  # action: nil,
  # changes: %{
  #   child: #Ecto.Changeset<
  #     action: :insert,
  #     changes: %{age: 30, name: "Gob"},
  #     errors: [],
  #     data: #Parent.Child<>,
  #     valid?: true
  #   >,
  #   name: "George"
  # },
  # errors: [],
  # data: #Parent<>,
  # valid?: true
  # >
  def test do
    new_parent = %{
      name: "George",
      child: %{
        name: "Gob",
        age: 30
      }
    }

    Parent.changeset(%Parent{}, new_parent)
  end

  # ** (Ecto.CastError) expected params to be a :map, got: `[%{age: 30, name: "Gob"}]`
  #   (ecto 3.5.7) lib/ecto/changeset.ex:514: Ecto.Changeset.cast/6
  #   (ecto 3.5.7) lib/ecto/changeset/relation.ex:129: Ecto.Changeset.Relation.do_cast/6
  #   (ecto 3.5.7) lib/ecto/changeset/relation.ex:318: Ecto.Changeset.Relation.single_change/5
  #   (ecto 3.5.7) lib/ecto/changeset/relation.ex:113: Ecto.Changeset.Relation.cast/5
  #   (ecto 3.5.7) lib/ecto/changeset.ex:811: Ecto.Changeset.cast_relation/4
  def test_bad_input do
    new_parent = %{
      name: "George",
      child: [%{
        name: "Gob",
        age: 30
      }]
    }

    Parent.changeset(%Parent{}, new_parent)
  end
end
```

When the embedded relationship is (incorrectly) defined as an array, (see: `Parent.test_bad_input()`) then an `Ecto.CastError` is raised.  

### Expected behavior

Ideally this would somehow be handled and an invalid `Ecto.Changeset` object would be returned.  This way the validation result handling code stays nice and simple and there is no reason to wrap anything in any sort of `try` / `rescue` construct.

At this point I am mainly interested in whether the larger group also considers this an issue.

### PR DESCRIPTION
**Pull request by v0idpwn**
Closes #3557.

### CODE REVIEW

File: lib/ecto/changeset/relation.ex [hunk 1]
```diff
@@ -95,6 +95,14 @@ defmodule Ecto.Changeset.Relation do
     end
   end
 
+  def cast(%{cardinality: :one} = relation, owner, params, current, on_cast) when is_list(params) do
+    if Keyword.keyword?(params) do
+      cast(relation, owner, Map.new(params), current, on_cast)
```
Comment (v0idpwn) [inline lib/ecto/changeset/relation.ex:100]: Required the keyword check because we allow keyword lists to be cast to embedded schemas

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by ChezCrawford** [comment]
Thanks for fixing this @v0idpwn!
