### PR TITLE
Recursively search for parent_as binding

### LINKED ISSUE #3619: Can't find named binding in CTE subquery with parent_as/1
### Environment

* Elixir version: 1.11.3
* Database and version: PostgreSQL 13
* Ecto version: 3.6.1
* Database adapter and version: postgrex 0.15.8
* Operating system: Arch Linux Kernel 5.11.15

### Current behavior

I'm trying to convert the following query from SQL to elixir:

```sql
SELECT g."name", breadcrumbs."names" AS "query_test" FROM "groups" AS g
LEFT JOIN LATERAL (
  -- breadcrumbs_query
  WITH RECURSIVE "breadcrumbs" AS (
    -- breadcrumbs_initial_query
    SELECT sg0."id", sg0."name", sg0."supergroup_id" FROM "groups" AS sg0
    WHERE sg0."id" = g."id"
    UNION ALL (
      -- breadcrumbs_recursion_query
      SELECT sg1."id", sg1."name", sg1."supergroup_id" FROM "groups" AS sg1
      INNER JOIN "breadcrumbs" AS b ON b."supergroup_id" = sg1."id"
    )
  )
  SELECT array_agg("name") AS "names" FROM "breadcrumbs"
) AS breadcrumbs ON TRUE;
```

Sample result:

```
+-----------------------+------------------------------------------------------------------------+
| name                  | query_test                                                             |
|-----------------------+------------------------------------------------------------------------|
| Supergroup            | ['Supergroup']                                                         |
| Subgroup 1            | ['Subgroup 1', 'Supergroup']                                           |
| Subgroup 1.1          | ['Subgroup 1.1', 'Subgroup 1', 'Supergroup']                           |
| Subgroup 1.1.1        | ['Subgroup 1.1.1', 'Subgroup 1.1', 'Subgroup 1', 'Supergroup']         |
| Subgroup 1.1.2        | ['Subgroup 1.1.2', 'Subgroup 1.1', 'Subgroup 1', 'Supergroup']         |
+-----------------------+------------------------------------------------------------------------+
```

And here's the query in elixir:

```elixir
def list_breadcrumbs do
  breadcrumbs_initial_query =
    Group
    |> where([g], g.id == parent_as(:group).id)

  breadcrumbs_recursion_query =
    Group
    |> join(:inner, [g], b in "breadcrumbs", on: b.supergroup_id == g.id)

  breadcrumbs_cte_query =
    breadcrumbs_initial_query
    |> union_all(^breadcrumbs_recursion_query)

  breadcrumbs_query =
    "breadcrumbs"
    |> recursive_ctes(true)
    |> with_cte("breadcrumbs", as: ^breadcrumbs_cte_query)
    |> select([b], %{names: fragment("array_agg(?)", b.name)})

  Repo.all from g in Group,
    as: :group,
    left_lateral_join: b in subquery(breadcrumbs_query),
    select: %{name: g.name, query_test: b.names}
end
```

But I can't access the `:group` binding:

```
** (Ecto.SubQueryError) the following exception happened when compiling a subquery.

    ** (Ecto.QueryError) `parent_as(:group)` can only be used in subqueries in query:
    
    from g0 in MyApp.Groups.Group,
      where: g0.id == parent_as(:group).id,
      union_all: (from g0 in MyApp.Groups.Group,
      join: b1 in "breadcrumbs",
      on: b1.supergroup_id == g0.id,
      select: g0),
      select: g0
    

The subquery originated from the following query:

from g0 in MyApp.Groups.Group,
  as: :group,
  left_join_lateral: b1 in subquery(from b0 in "breadcrumbs",
  select: %{names: fragment("array_agg(?)", b0.name)}),
  on: true,
  select: %{name: g0.name, query_test: b1.names}

    (elixir 1.11.3) lib/enum.ex:1533: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto 3.6.1) lib/ecto/repo/queryable.ex:208: Ecto.Repo.Queryable.execute/4
    (ecto 3.6.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
```

 I also tried using `as/1` but I get an error saying that the binding could not be found.

### Expected behavior

I expected the `:group` binding to be available.

### PR DESCRIPTION
**Pull request by v0idpwn**
Work in progress attempt to fix #3619.

### CODE REVIEW

**Comment by v0idpwn** [comment]
I did some tests and this makes me able to use `parent_as` from chained subqueries. Yet it feels so simple it must be wrong 🤔

File: test/ecto/query/planner_test.exs [hunk 1]
```diff
@@ -824,11 +824,22 @@ defmodule Ecto.Query.PlannerTest do
...
+  test "normalize: nested parent_as" do
+    child3 = from(c in Comment, where: parent_as(:posts).deleted == false, select: c.id)
+    child2 = from(c in Comment, where: c.id in subquery(child3), select: c.id)
+    child = from(c in Comment, where: parent_as(:posts).posted == c.posted and c.id in subquery(child2))
+
+    query = from(Post, as: :posts, join: c in subquery(child)) |> normalize()
+    assert Macro.to_string(hd(hd(query.joins).source.query.wheres).expr) =~ "parent_as(&0).posted() == &0.posted()"
+    assert Macro.to_string(hd(hd(query.joins).source.query.wheres).expr) =~ "in %Ecto.SubQuery{"
+  end
+
```
Comment (v0idpwn) [inline test/ecto/query/planner_test.exs:841]: This is not a good test. How can I improve it?

Comment (josevalim) [reply test/ecto/query/planner_test.exs:841]: It looks OK to me. The rest of the work needs to be done in ecto_sql to make it recursively.

File: lib/ecto/query/planner.ex [hunk 2]
```diff
@@ -1631,11 +1631,11 @@ defmodule Ecto.Query.Planner do
           {ix, {:parent_as, [], [{:&, meta, [ix]}]}, query}
         end
 
-      %{} ->
-        error!(query, "could not find named binding `parent_as(#{inspect(as)})`")
+      %{} = parent ->
+        get_ix!({:parent_as, meta, [as]}, kind, parent)
```
Comment (josevalim) [inline lib/ecto/query/planner.ex:1635]: I am wondering if it is better to make it recursive on the way down. I.e. as we go into the subquery, we merge the current as with the parent as.

Comment (v0idpwn) [reply lib/ecto/query/planner.ex:1635]: What advantage does this offer over this approach? 

I thought about it, but it would add a cost in all multi-level queries with aliases, while this approach adds a cost only when there is no `parent_as` available at a level. It would indeed give better errors, tho.

File: test/ecto/query/planner_test.exs (hunk 1 above)
Comment (v0idpwn) [reply test/ecto/query/planner_test.exs:841]: I wrote a simple integration test and it seems to be working out of the box (on postgres). Didn't commit it because I'm not sure about where it belongs.

File: lib/ecto/query/planner.ex (hunk 2 above)
Comment (josevalim) [reply lib/ecto/query/planner.ex:1635]: I think the best is to write them as unit tests in ecto_sql. :)

File: test/ecto/query/planner_test.exs (hunk 1 above)
Comment (josevalim) [reply test/ecto/query/planner_test.exs:841]: Hrm, good call. Sounds good to me then.

Comment (josevalim) [reply test/ecto/query/planner_test.exs:841]: I think the best is to write them as unit tests in ecto_sql. :)

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
