### PR TITLE
Convert map keys to int before sorting

### LINKED ISSUE #1771: `cast_embed` / `cast_assoc` sorts list elements wrong when given a map
As discussed with @ericmj on IRC this is probably, maybe a bug.

Given the following schema:

```elixir
defmodule Post do
  schema "posts" do
    embeds_many :categories, Category
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast_embed(:categories)
  end
end
```

With these params

```
posts[categories][1][title] = 'thing'
posts[categories][2][title] = 'other thing'
# ...
posts[categories][10][title] = 'totally different thing'
```

Correctly turns the categories into a list but it sorts them wrong. The indexes are strings and (of course) sorted like that. So it ends up like `1, 10, 11, 2, 3, ...` and so on.

In my app I manually convert the indexes to ints before casting but maybe ecto should do this by itself as it is already _trying_ to sort them (see https://github.com/elixir-ecto/ecto/blob/v2.0.5/lib/ecto/changeset/relation.ex#L84-L87)

### PR DESCRIPTION
**Pull request by mikker**
Fix #1771

### CODE REVIEW

File: lib/ecto/changeset/relation.ex [hunk 1]
```diff
@@ -83,11 +83,20 @@ defmodule Ecto.Changeset.Relation do
...
       params
-      |> Enum.sort_by(&elem(&1, 0))
+      |> Enum.sort_by(&key_as_int/1)
       |> Enum.map(&elem(&1, 1))
     cast(relation, params, current, on_cast)
   end
 
+  defp key_as_int({key, _}) when is_binary(key) do
+    try do
+      String.to_integer(key)
```
Comment (josevalim) [inline lib/ecto/changeset/relation.ex]: We should use `Integer.parse` and return the key unchanged if we can't parse it. That's because there is no requirement for string keys to represent integers.

Comment (mikker) [inline lib/ecto/changeset/relation.ex]: People on IRC suggested using something faster than `Integer.parse`. Is that a valid concern?

File: lib/ecto/changeset/relation.ex [hunk 2]
```diff
@@ -324,6 +325,14 @@ defmodule Ecto.Changeset.Relation do
     end
   end
 
+  defp key_as_int({key, val}) when is_binary(key) do
+    case Integer.parse(key) do
+      {key, _} -> {key, val}
```
Comment (josevalim) [inline lib/ecto/changeset/relation.ex]: It should be rather:

```elixir
case Integer.parse(key) do
  {key, ""} -> {key, val}
  _ -> {key, val}
end
```

Otherwise we will convert strings starting with numbers and discard the rest of the string.

File: lib/ecto/changeset/relation.ex [hunk 3]
```diff
@@ -83,7 +83,8 @@ defmodule Ecto.Changeset.Relation do
   def cast(%{cardinality: :many} = relation, params, current, on_cast) when is_map(params) do
     params =
       params
-      |> Enum.sort_by(&elem(&1, 0))
+      |> Enum.map(&key_as_int/1)
+      |> Enum.sort
```
Comment (shhavel) [inline lib/ecto/changeset/relation.ex]: I think it should be `Enum.sort_by(&elem(&1, 0))` istead of `Enum.sort`.
otherwise it will sort by values as well which is unnecessary (and slower), e.g.:

```elixir
iex> Enum.sort([%{"1" => "b"}, %{"1" => "a"}])
[%{"1" => "a"}, %{"1" => "b"}]
```

Comment (josevalim) [inline lib/ecto/changeset/relation.ex]: Yup, `Enum.sort` is fine. Plus it will only sort by value if the keys are different.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by mikker** [comment]
# Bucket list:

- [x] Got the hearts from Jose.
