### PR TITLE
 index/3 raises if given multiple `where:` clauses

### LINKED ISSUE #2690: `Ecto.Migration.index/3` silently mishandles multiple `:where` clauses
### Environment

* Elixir version (elixir -v): Elixir 1.7.1 (compiled with Erlang/OTP 21)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 10.2
* Ecto version (mix deps): 2.2.10
* Database adapter and version (mix deps): Postgrex 0.13.5
* Operating system: MacOS High Sierra (10.13.6)

## Problem

`Ecto.Query.from` allows multiple `where:` clauses. So it seems natural to use multiple `where:` clauses when creating an index with `Ecto.Migration`. However, doing so fails in a surprising way.

### Current behavior

This statement:

```elixir
    create(
      index(
        "seasons",
        :team_id,
        where: "started_at is not null",
        where: "ended_at is null",
        unique: true,
        name: "only_one_active_season_per_team"
      )
    )
```

...creates an index where only the second `where:` clause is used.

### Expected behavior

Either `index/3` should combine all `where:` clauses using `AND`, or it should raise an error when multiple `where:` clauses are given, suggesting that the user combine them.

### PR DESCRIPTION
**Pull request by nathanl**
Because multiple `where:` keywords are supported by Ecto.Query, users
may provide multiple `where:` keywords when declaring a partial index.
However, this is not supported.

Previously, this would fail in a surprising way: the final `where:`
would be used and the other discarded. Now we raise an error, explaining
that these clauses should be combined into a single string.

Fixes #2690

### CODE REVIEW

File: lib/ecto/migration.ex [hunk 1]
```diff
@@ -956,6 +960,21 @@ defmodule Ecto.Migration do
...
 
+  defp validate_index_opts!(opts) when is_list(opts) do
+    where_count = Enum.count(opts, fn entry ->
+      case entry do
+        {:where, _} -> true
+        _ -> false
+      end
+    end)
+    if where_count > 1 do
+      raise Index.Error, message:
```
Comment (josevalim) [inline lib/ecto/migration.ex]: We don't need a new exception for this, ArgumentError is fine

File: lib/ecto/migration.ex [hunk 2]
```diff
@@ -956,6 +960,21 @@ defmodule Ecto.Migration do
     reference
   end
 
+  defp validate_index_opts!(opts) when is_list(opts) do
+    where_count = Enum.count(opts, fn entry ->
```
Comment (josevalim) [inline lib/ecto/migration.ex]: Maybe:

```elixir
case Keyword.get_values(opts, :where) do
  [_, _ | _] -> raise ...
  _ -> :ok
end
```

**Comment by nathanl** [comment]
@josevalim Thanks for the feedback! Updated.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
