### PR TITLE
Use `Task.async_stream` to preload associations.

### LINKED ISSUE #2246: Preload with in_parallel=true links the client process to an internal ecto Task.async process
### Environment

* Elixir version: 1.5.1
* Database and version: PostgreSQL 9.4
* Ecto version: 2.1
* Database adapter and version: postgrex 0.13.3
* Operating system: Ubuntu

### Current behavior

I'm performing a query using preload with multiples associations in a process which has `trap_exit: true`. After the query ends the process receives a `{:EXIT, #PID<0.102.0>, :normal}` message which is really odd because this process doesn't have any linked processes.
I was able to reproduce this behavior with this example:
```elixir
import Ecto.Query
internal_order_number = "da8bfb94-41b8-4921-a537-749a1b3d0936"
f = fn ->
  Process.flag(:trap_exit, true)
  Order
  |> where([internal_number: ^internal_order_number]
  |> preload([:vertical, :promo_codes, :credit_usages])
  |> Repo.one
  receive do
   msg -> IO.puts("!!!!!!!!!! #{inspect msg}")
  end
end
spawn(f)
```
which logs:
`!!!!!!!!!! {:EXIT, #PID<0.102.0>, :normal}`

Tracing this message i  found that this message is produced when the `Task.async` ends [here](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo/preloader.ex#L108)

### Expected behavior

The `Task.async` should run within a supervisor in order to prevent the link between the task and the client process to not receive any `:EXIT` message from ecto

### PR DESCRIPTION
**Pull request by nashby**
This fixes #2246.

### CODE REVIEW

File: lib/ecto/repo/preloader.ex [hunk 1]
```diff
@@ -104,8 +104,8 @@ defmodule Ecto.Repo.Preloader do
       # set the proper timeouts.
       opts = Keyword.put_new(opts, :caller, self())
       assocs
-      |> Enum.map(&Task.async(:erlang, :apply, [fun, [&1, opts]]))
-      |> Enum.map(&Task.await(&1, :infinity))
+      |> Task.async_stream(&fun.(&1, opts))
+      |> Enum.map(fn {:ok, assoc} -> assoc end)
```
Comment (michalmuskala) [inline lib/ecto/repo/preloader.ex]: Let's use `Stream.map` - we have a stream anyway.

File: lib/ecto/repo/preloader.ex [hunk 2]
```diff
@@ -104,8 +104,8 @@ defmodule Ecto.Repo.Preloader do
       # set the proper timeouts.
       opts = Keyword.put_new(opts, :caller, self())
       assocs
-      |> Enum.map(&Task.async(:erlang, :apply, [fun, [&1, opts]]))
-      |> Enum.map(&Task.await(&1, :infinity))
+      |> Task.async_stream(&fun.(&1, opts))
```
Comment (ericmj) [inline lib/ecto/repo/preloader.ex]: :timeout should still be :infinity I guess.

File: lib/ecto/repo/preloader.ex (hunk 1 above)
Comment (nashby) [reply lib/ecto/repo/preloader.ex]: @michalmuskala thanks, changed.

Comment (ericmj) [reply lib/ecto/repo/preloader.ex]: I think it's better evaluate the function in one place instead of somtimes returning a list and sometimes returning a stream. Enum.map should be faster as well if that matters.

File: lib/ecto/repo/preloader.ex (hunk 2 above)
Comment (nashby) [reply lib/ecto/repo/preloader.ex]: @ericmj yep, makes sense. Added!

File: lib/ecto/repo/preloader.ex (hunk 1 above)
Comment (josevalim) [reply lib/ecto/repo/preloader.ex]: @michalmuskala we should stick with `Enum.map` because we want to realize the computation now and not later on.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

File: lib/ecto/repo/preloader.ex [hunk 3]
```diff
@@ -104,8 +104,8 @@ defmodule Ecto.Repo.Preloader do
       # set the proper timeouts.
       opts = Keyword.put_new(opts, :caller, self())
       assocs
-      |> Enum.map(&Task.async(:erlang, :apply, [fun, [&1, opts]]))
-      |> Enum.map(&Task.await(&1, :infinity))
+      |> Task.async_stream(&fun.(&1, opts), timeout: :infinity)
```
Comment (AndrewDryga) [inline lib/ecto/repo/preloader.ex]: @michalmuskala  do we really want to have `:infinity` timeout here? What if preload takes too long?

Comment (michalmuskala) [reply lib/ecto/repo/preloader.ex]: We already have timeouts on the query level, we don't need to double them here as well.
