### PR TITLE
Raise on literal non-base binary/uuids in query

### LINKED ISSUE #4289: Query fails to encode on literal UUID
### Elixir version

All

### Database and Version

PostgreSQL (all)

### Ecto Versions

All

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex

### Current behavior

A query on a Ecto.UUID field, where the UUID is literal, emits SQL with invalid bytes:

```
where([s], s.uuid == "017f65d1-80bd-152d-f997-afa6dd33a00f")
```

The reason why this happens is because the Planner calls Ecto.UUID.dump, which returns a binary, which we then promptly inject into the query.

Ecto actually has a mechanism to deal with these, called Ecto.Query.Tagged, and the original parameter is wrapped in such a struct, but the struct is removed during the Planner.prewalk time. The only reason why this doesn't happen to binaries is because we explicit keep the tagged struct:

```
  defp prewalk(%Ecto.Query.Tagged{value: v, type: type} = tagged, kind, query, expr, acc, adapter) do
    if Ecto.Type.base?(type) do
      {tagged, acc}
    else
      {dump_param(kind, query, expr, v, type, adapter), acc}
    end
  end
```

### Expected behavior

We should probably dump the param and check its underlying type, if the value is a string and the underlying type is not a string (or any), then we should probably keep the tagged struct. Note we would still need to support Tagged UUIDs in EctoSQL.

### PR DESCRIPTION
**Pull request by josevalim**
Closes #4289.
Closes https://github.com/elixir-ecto/ecto_sql/issues/520.

### CODE REVIEW

**Review by v0idpwn — APPROVED** [review]
I like this approach better than all alternatives considered.

File: lib/ecto/query/planner.ex [hunk 1]
```diff
@@ -1309,7 +1309,28 @@ defmodule Ecto.Query.Planner do
     if Ecto.Type.base?(type) do
       {tagged, acc}
     else
-      {dump_param(kind, query, expr, v, type, adapter), acc}
+      type = field_type!(kind, query, expr, type)
```
Comment (greg-rychlewski) [inline lib/ecto/query/planner.ex:1312]: Sorry if this is noise but I remember playing around with this and you might have to call `Ecto.Type.type` on this to get `:uuid`? Otherwise I think it will be `Ecto.UUID`

**Comment by greg-rychlewski** [comment]
I agree this is the cleanest approach.

File: lib/ecto/query/planner.ex (hunk 1 above)
Comment (josevalim) [reply lib/ecto/query/planner.ex:1312]: It is all good as is. `field_type` gets the type from a field, which may still be `Ecto.UUID`. But the Ecto.Type calls always reserve the type properly. :)

Comment (greg-rychlewski) [reply lib/ecto/query/planner.ex:1312]: oh you are already considering that below. ignore me!

**Review by greg-rychlewski — APPROVED** [review]

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by greg-rychlewski** [comment]
One thing I forgot to mention is that the old behaviour worked fine for MySQL so this will be a breaking change for them. I'm guessing it's a fair trade to have greater library stability. Just wanted to mention it.

**Comment by josevalim** [comment]
Perfect, we will include it in the changelog. And it was probably fine for mysql query wise, although if the query was logged anywhere, it would be invalid utf8 and likely cause other breakages.
